#!/usr/bin/env node

var table = require('text-table');
var program = require('commander');
var moment = require('moment');
var fs = require('fs');
var path = require('path');
var request = require('request');
var exec = require('child_process').execFile;

var algoliasearch = require('algoliasearch');

program
  .version('1.1.6')
  .usage('[options] <search ...>')
  .description('Blazing fast Meteor packages search cli powered by Algolia.')
  .option('-g, --github', 'display GitHub url')
  .option('-l, --long', 'display long format')
  .option('-n, --nbhits <n>', 'number of results (default: 10)', parseInt);

program.on('--help', function help() {
  console.log('  Examples:');
  console.log('');
  console.log('    $ fastosphere acemtp -g   # Display GitHub link (⌘  + click on it to open the url)');
  console.log('    $ fastosphere router -n 20  # Display 20 results');
});

program.parse(process.argv);

// console.log('prog', program, program.nbhits);

var query = program.args.join(' ');

var client = algoliasearch('10L80F1AT7', 'b72cb5333cc8de90e7217eee27c48c63');

var index = client.initIndex('Packages');

var nbhits = program.nbhits || 10;

index.search(query, { hitsPerPage: nbhits }, function (error, content) {

  if (error) {
    console.error("Error :", error.message);
    process.exit(1);
  }

//  console.log(content.hits);
  if (!content.hits.length) console.log('No Meteor package found for', query);

  var hits = [];
  content.hits.forEach(function fe(h) {
    var a = [];
    if (program.long) {
      if (h.downloadCounts) a.push((h.downloadCounts.directAdds || 0) + '/' + (h.downloadCounts.lastMonthDirectAdds || 0) + '/' + (h.downloadCounts.lastWeekDirectAdds || 0) + '⬇');
      a.push(h.starCount ? h.starCount + '/' + h.gitStarCount + '/' + h.atmoStarCount + '★' : '');
    } else {
      a.push((h.downloadCounts.directAdds || 0) + '⬇');
      a.push((h.starCount || 0) + '★');
    }
    a.push(h.name);
    a.push(h.version || '');
    a.push(moment(h.lastUpdated).fromNow());

    var desc = h.description;
    var width = program.github ? 50 : 100;
    if (desc.length > width) {
      desc = desc.substr(0, width - 3) + '...';
    }
    a.push(desc);

    if (program.github) a.push(h.gitUrl || '');

    hits.push(a);
  });

  console.log(table(hits));
  process.exit();
});
